//! Bring-up diagnostics: UART tracing for the `usb-diag` and `stack-probe`
//! cargo features, both default-off.
//!
//! Every function here has a real implementation under its feature and an
//! `#[inline]` no-op twin without it, so call sites in main.rs stay
//! unconditional and the loop body reads as production control flow. Same
//! pattern usb_msc.rs uses internally.
//!
//! Generic over `W: core::fmt::Write` rather than over `Serial0`: `Serial0`
//! is generated by `impl_tiliqua_soc_pac!()` in the binary crate and is not
//! nameable from here.

#[cfg(any(feature = "stack-probe", feature = "usb-diag"))]
use core::fmt::Write;

use crate::usb_msc::UsbMsc;

// ---------------------------------------------------------------- stack-probe

/// Paint the region between the end of .bss and the current stack pointer
/// with a sentinel byte, so `stack_scan` can find the high-water mark
/// (M6_USB_STORAGE.md §7a).
///
/// # Safety
/// Call once, early in `main()`, before any deep call. Leaves a 256-byte
/// margin below the live frame so the caller's own locals are not clobbered.
#[cfg(feature = "stack-probe")]
pub fn stack_paint<W: Write>(ser: &mut W) {
    unsafe {
        extern "C" {
            static _eheap: u8;
            static _stack_start: u8;
        }
        let low = &_eheap as *const u8 as usize;
        let sp: usize;
        core::arch::asm!("mv {0}, sp", out(reg) sp);
        // Leave a safety margin below the live call frame so we don't
        // clobber locals `main()` has already pushed getting here.
        let paint_until = sp.saturating_sub(256);
        if paint_until > low {
            core::ptr::write_bytes(low as *mut u8, 0xAA, paint_until - low);
        }
    }
    ser.write_str("\r\nstack-paint probe armed\r\n").ok();
}

#[cfg(not(feature = "stack-probe"))]
#[inline]
pub fn stack_paint<W>(_ser: &mut W) {}

/// Scan for the stack high-water mark every 64th call and log only growth.
/// A full-region byte scan every iteration would be wasteful for a
/// menu-driven loop.
#[cfg(feature = "stack-probe")]
pub fn stack_scan<W: Write>(ser: &mut W, max: &mut usize, ctr: &mut u32) {
    *ctr = ctr.wrapping_add(1);
    if !ctr.is_multiple_of(64) {
        return;
    }
    unsafe {
        extern "C" {
            static _eheap: u8;
            static _stack_start: u8;
        }
        let low = &_eheap as *const u8 as usize;
        let high = &_stack_start as *const u8 as usize;
        let mut addr = low;
        while addr < high && *(addr as *const u8) == 0xAA {
            addr += 1;
        }
        let used = high - addr;
        if used > *max {
            *max = used;
            let mut msg: heapless::String<48> = heapless::String::new();
            let _ = write!(msg, "stack peak: {} / {} B\r\n", used, high - low);
            ser.write_str(msg.as_str()).ok();
        }
    }
}

#[cfg(not(feature = "stack-probe"))]
#[inline]
pub fn stack_scan<W>(_ser: &mut W, _max: &mut usize, _ctr: &mut u32) {}

// ------------------------------------------------------------------- usb-diag

/// Last-seen MSC status, so `usb_status` only prints on a transition.
#[cfg(feature = "usb-diag")]
#[derive(Default, PartialEq, Eq, Clone, Copy)]
pub struct UsbStatusSnap {
    connected: bool,
    ready: bool,
    block_size: u16,
}

#[cfg(not(feature = "usb-diag"))]
#[derive(Default)]
pub struct UsbStatusSnap;

/// Log MSC status transitions. A watchdog reset / re-enumeration cycle shows
/// up here as conn/rdy flapping; steady state prints once and goes quiet
/// (constant drive-LED blinking otherwise unexplained).
#[cfg(feature = "usb-diag")]
pub fn usb_status<W: Write>(ser: &mut W, msc: &UsbMsc, last: &mut UsbStatusSnap) {
    let snap = UsbStatusSnap {
        connected: msc.connected(),
        ready: msc.ready(),
        block_size: msc.block_size(),
    };
    if snap == *last {
        return;
    }
    *last = snap;
    let mut msg: heapless::String<80> = heapless::String::new();
    let _ = write!(
        msg,
        "usb: conn={} rdy={} bs={} spd={} t={}ms\r\n",
        snap.connected as u8,
        snap.ready as u8,
        snap.block_size,
        msc.speed(),
        crate::uptime::now_ms()
    );
    ser.write_str(msg.as_str()).ok();
}

#[cfg(not(feature = "usb-diag"))]
#[inline]
pub fn usb_status<W>(_ser: &mut W, _msc: &UsbMsc, _last: &mut UsbStatusSnap) {}

/// Counter baseline captured at `export_begin`, so `export_result` can report
/// deltas for this attempt rather than lifetime totals.
#[cfg(feature = "usb-diag")]
#[derive(Default, Clone, Copy)]
pub struct ExportSnap {
    rd: u32,
    rd_err: u32,
    wr: u32,
    wr_ok: u32,
    wr_notready: u32,
    wr_resp_err: u32,
    wr_timeout: u32,
    wr_conn_lost: u32,
}

#[cfg(not(feature = "usb-diag"))]
#[derive(Default)]
pub struct ExportSnap;

/// Latch the first failure of this export attempt and snapshot the counters.
#[cfg(feature = "usb-diag")]
pub fn export_begin<W: Write>(ser: &mut W, msc: &UsbMsc, fname: &str, got: bool) -> ExportSnap {
    let d = &msc.diag;
    d.begin(); // capture FIRST failure of this attempt
    let snap0 = ExportSnap {
        rd: d.rd.get(),
        rd_err: d.rd_err.get(),
        wr: d.wr.get(),
        wr_ok: d.wr_ok.get(),
        wr_notready: d.wr_notready.get(),
        wr_resp_err: d.wr_resp_err.get(),
        wr_timeout: d.wr_timeout.get(),
        wr_conn_lost: d.wr_conn_lost.get(),
    };
    let mut msg: heapless::String<96> = heapless::String::new();
    let _ = write!(
        msg,
        "export: begin {} got={} rdy={} conn={} bs={}\r\n",
        fname,
        got as u8,
        msc.ready() as u8,
        msc.connected() as u8,
        msc.block_size()
    );
    ser.write_str(msg.as_str()).ok();
    snap0
}

#[cfg(not(feature = "usb-diag"))]
#[inline]
pub fn export_begin<W>(_ser: &mut W, _msc: &UsbMsc, _fname: &str, _got: bool) -> ExportSnap {
    ExportSnap
}

/// Per-stage export outcome: counter deltas, first-and-last CSW/reject
/// snapshots, sense data, and the round-six read-failure detail.
#[cfg(feature = "usb-diag")]
pub fn export_result<W: Write>(
    ser: &mut W,
    msc: &UsbMsc,
    ok: bool,
    mounted: bool,
    snap0: &ExportSnap,
) {
    let d = &msc.diag;
    {
        let mut msg: heapless::String<320> = heapless::String::new();
        let _ = write!(
            msg,
            "export: ok={} mount={} d_rd={} d_rderr={} d_wr={} \
             d_wrok={} d_wrnrdy={} d_wrerr={} d_wrto={} d_wrconn={} \
             spins={} wms={}\r\n",
            ok as u8,
            mounted as u8,
            d.rd.get().wrapping_sub(snap0.rd),
            d.rd_err.get().wrapping_sub(snap0.rd_err),
            d.wr.get().wrapping_sub(snap0.wr),
            d.wr_ok.get().wrapping_sub(snap0.wr_ok),
            d.wr_notready.get().wrapping_sub(snap0.wr_notready),
            d.wr_resp_err.get().wrapping_sub(snap0.wr_resp_err),
            d.wr_timeout.get().wrapping_sub(snap0.wr_timeout),
            d.wr_conn_lost.get().wrapping_sub(snap0.wr_conn_lost),
            d.wr_spins_last.get(),
            d.wr_ms_last.get()
        );
        let (cs, cr) = d.wr_csw.get();
        let (rr, rp, rt, rn, rl) = d.wr_reject.get();
        let (fcs, fcr) = d.wr_csw_first.get();
        let (frr, frp, frt, frn, frl) = d.wr_reject_first.get();
        let (sv, sk, sa, sq) = msc.sense_info();
        let _ = write!(
            msg,
            "export: first csw={}/{} rej={}/{}/{} ny={} lph={} \
             last csw={}/{} rej={}/{}/{} ny={} lph={}\r\n\
             export: sense valid={} key={:x} asc={:02x} ascq={:02x}\r\n",
            fcs, fcr, frr, frp, frt, frn, frl, cs, cr, rr, rp, rt, rn, rl, sv as u8, sk, sa, sq
        );
        ser.write_str(msg.as_str()).ok();
    }
    {
        // Round-six read-failure diag: reason 1=notready 2=resp_err
        // 3=deadline 4=conn_lost, at word w of lba, after sp spins;
        // rej/ny/lph = reject_info CSR snapshot at the failure.
        let f1 = d.rd_fail_first.get();
        let f2 = d.rd_fail.get();
        let path1 = d.rd_path_first.get();
        let path2 = d.rd_path.get();
        let ms1 = d.rd_ms_first.get();
        let ms2 = d.rd_ms.get();
        let mut msg: heapless::String<256> = heapless::String::new();
        let _ = write!(
            msg,
            "export: rd1 rsn={} w={} lba={} sp={} ms={} \
             rej={}/{} ny={} lph={} pth={:08x}\r\n\
             export: rdL rsn={} w={} lba={} sp={} ms={} \
             rej={}/{} ny={} lph={} pth={:08x}\r\n",
            f1.reason,
            f1.word,
            f1.lba,
            f1.spins,
            ms1,
            f1.reject.response,
            f1.reject.phase,
            f1.reject.nyets,
            f1.reject.last_phase,
            path1,
            f2.reason,
            f2.word,
            f2.lba,
            f2.spins,
            ms2,
            f2.reject.response,
            f2.reject.phase,
            f2.reject.nyets,
            f2.reject.last_phase,
            path2
        );
        ser.write_str(msg.as_str()).ok();
    }
}

#[cfg(not(feature = "usb-diag"))]
#[inline]
pub fn export_result<W>(
    _ser: &mut W,
    _msc: &UsbMsc,
    _ok: bool,
    _mounted: bool,
    _snap0: &ExportSnap,
) {
}
