#![doc = "Peripheral access API for SOC microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn TIMER0();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[no_mangle]
pub static __EXTERNAL_INTERRUPTS: [Vector; 1] = [Vector { _handler: TIMER0 }];
#[doc(hidden)]
pub mod interrupt;
pub use self::interrupt::Interrupt;
#[doc = "spiflash_ctrl"]
pub type SPIFLASH_CTRL = crate::Periph<spiflash_ctrl::RegisterBlock, 0xf000_0100>;
impl core::fmt::Debug for SPIFLASH_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SPIFLASH_CTRL").finish()
    }
}
#[doc = "spiflash_ctrl"]
pub mod spiflash_ctrl;
#[doc = "uart0"]
pub type UART0 = crate::Periph<uart0::RegisterBlock, 0xf000_0200>;
impl core::fmt::Debug for UART0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("UART0").finish()
    }
}
#[doc = "uart0"]
pub mod uart0;
#[doc = "timer0"]
pub type TIMER0 = crate::Periph<timer0::RegisterBlock, 0xf000_0300>;
impl core::fmt::Debug for TIMER0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("TIMER0").finish()
    }
}
#[doc = "timer0"]
pub mod timer0;
#[doc = "i2c0"]
pub type I2C0 = crate::Periph<i2c0::RegisterBlock, 0xf000_0404>;
impl core::fmt::Debug for I2C0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C0").finish()
    }
}
#[doc = "i2c0"]
pub mod i2c0;
#[doc = "i2c1"]
pub type I2C1 = crate::Periph<i2c1::RegisterBlock, 0xf000_0504>;
impl core::fmt::Debug for I2C1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2C1").finish()
    }
}
#[doc = "i2c1"]
pub mod i2c1;
#[doc = "encoder0"]
pub type ENCODER0 = crate::Periph<encoder0::RegisterBlock, 0xf000_0600>;
impl core::fmt::Debug for ENCODER0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ENCODER0").finish()
    }
}
#[doc = "encoder0"]
pub mod encoder0;
#[doc = "pmod0_periph"]
pub type PMOD0_PERIPH = crate::Periph<pmod0_periph::RegisterBlock, 0xf000_0700>;
impl core::fmt::Debug for PMOD0_PERIPH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PMOD0_PERIPH").finish()
    }
}
#[doc = "pmod0_periph"]
pub mod pmod0_periph;
#[doc = "dtr0"]
pub type DTR0 = crate::Periph<dtr0::RegisterBlock, 0xf000_0800>;
impl core::fmt::Debug for DTR0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DTR0").finish()
    }
}
#[doc = "dtr0"]
pub mod dtr0;
#[doc = "persist_periph"]
pub type PERSIST_PERIPH = crate::Periph<persist_periph::RegisterBlock, 0xf000_0900>;
impl core::fmt::Debug for PERSIST_PERIPH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PERSIST_PERIPH").finish()
    }
}
#[doc = "persist_periph"]
pub mod persist_periph;
#[doc = "palette_periph"]
pub type PALETTE_PERIPH = crate::Periph<palette_periph::RegisterBlock, 0xf000_0a00>;
impl core::fmt::Debug for PALETTE_PERIPH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PALETTE_PERIPH").finish()
    }
}
#[doc = "palette_periph"]
pub mod palette_periph;
#[doc = "framebuffer_periph"]
pub type FRAMEBUFFER_PERIPH = crate::Periph<framebuffer_periph::RegisterBlock, 0xf000_0b00>;
impl core::fmt::Debug for FRAMEBUFFER_PERIPH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FRAMEBUFFER_PERIPH").finish()
    }
}
#[doc = "framebuffer_periph"]
pub mod framebuffer_periph;
#[doc = "psram_csr"]
pub type PSRAM_CSR = crate::Periph<psram_csr::RegisterBlock, 0xf000_0c00>;
impl core::fmt::Debug for PSRAM_CSR {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PSRAM_CSR").finish()
    }
}
#[doc = "psram_csr"]
pub mod psram_csr;
#[doc = "pixel_plot"]
pub type PIXEL_PLOT = crate::Periph<pixel_plot::RegisterBlock, 0xf000_0d00>;
impl core::fmt::Debug for PIXEL_PLOT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PIXEL_PLOT").finish()
    }
}
#[doc = "pixel_plot"]
pub mod pixel_plot;
#[doc = "blit"]
pub type BLIT = crate::Periph<blit::RegisterBlock, 0xf000_0e00>;
impl core::fmt::Debug for BLIT {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("BLIT").finish()
    }
}
#[doc = "blit"]
pub mod blit;
#[doc = "line"]
pub type LINE = crate::Periph<line::RegisterBlock, 0xf000_0f00>;
impl core::fmt::Debug for LINE {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("LINE").finish()
    }
}
#[doc = "line"]
pub mod line;
#[doc = "sid_periph"]
pub type SID_PERIPH = crate::Periph<sid_periph::RegisterBlock, 0xf000_1000>;
impl core::fmt::Debug for SID_PERIPH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SID_PERIPH").finish()
    }
}
#[doc = "sid_periph"]
pub mod sid_periph;
#[doc = "play_timer"]
pub type PLAY_TIMER = crate::Periph<play_timer::RegisterBlock, 0xf000_1100>;
impl core::fmt::Debug for PLAY_TIMER {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PLAY_TIMER").finish()
    }
}
#[doc = "play_timer"]
pub mod play_timer;
#[doc = "usb_msc"]
pub type USB_MSC = crate::Periph<usb_msc::RegisterBlock, 0xf000_1200>;
impl core::fmt::Debug for USB_MSC {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("USB_MSC").finish()
    }
}
#[doc = "usb_msc"]
pub mod usb_msc;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "spiflash_ctrl"]
    pub SPIFLASH_CTRL: SPIFLASH_CTRL,
    #[doc = "uart0"]
    pub UART0: UART0,
    #[doc = "timer0"]
    pub TIMER0: TIMER0,
    #[doc = "i2c0"]
    pub I2C0: I2C0,
    #[doc = "i2c1"]
    pub I2C1: I2C1,
    #[doc = "encoder0"]
    pub ENCODER0: ENCODER0,
    #[doc = "pmod0_periph"]
    pub PMOD0_PERIPH: PMOD0_PERIPH,
    #[doc = "dtr0"]
    pub DTR0: DTR0,
    #[doc = "persist_periph"]
    pub PERSIST_PERIPH: PERSIST_PERIPH,
    #[doc = "palette_periph"]
    pub PALETTE_PERIPH: PALETTE_PERIPH,
    #[doc = "framebuffer_periph"]
    pub FRAMEBUFFER_PERIPH: FRAMEBUFFER_PERIPH,
    #[doc = "psram_csr"]
    pub PSRAM_CSR: PSRAM_CSR,
    #[doc = "pixel_plot"]
    pub PIXEL_PLOT: PIXEL_PLOT,
    #[doc = "blit"]
    pub BLIT: BLIT,
    #[doc = "line"]
    pub LINE: LINE,
    #[doc = "sid_periph"]
    pub SID_PERIPH: SID_PERIPH,
    #[doc = "play_timer"]
    pub PLAY_TIMER: PLAY_TIMER,
    #[doc = "usb_msc"]
    pub USB_MSC: USB_MSC,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            SPIFLASH_CTRL: SPIFLASH_CTRL::steal(),
            UART0: UART0::steal(),
            TIMER0: TIMER0::steal(),
            I2C0: I2C0::steal(),
            I2C1: I2C1::steal(),
            ENCODER0: ENCODER0::steal(),
            PMOD0_PERIPH: PMOD0_PERIPH::steal(),
            DTR0: DTR0::steal(),
            PERSIST_PERIPH: PERSIST_PERIPH::steal(),
            PALETTE_PERIPH: PALETTE_PERIPH::steal(),
            FRAMEBUFFER_PERIPH: FRAMEBUFFER_PERIPH::steal(),
            PSRAM_CSR: PSRAM_CSR::steal(),
            PIXEL_PLOT: PIXEL_PLOT::steal(),
            BLIT: BLIT::steal(),
            LINE: LINE::steal(),
            SID_PERIPH: SID_PERIPH::steal(),
            PLAY_TIMER: PLAY_TIMER::steal(),
            USB_MSC: USB_MSC::steal(),
        }
    }
}
